theme: jekyll-theme-cayman
title: Pavan Kumar Mangalapally's personal site
description: This is a place for me to expression my opinions. My opinions are 100% with my own imaginations and past experience.